services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./nginx-docker.conf:/etc/nginx/nginx.conf:ro"
      - "./nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt:ro"
      - "./nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key:ro"
    networks:
      - daniel
    depends_on:
      - frontend
      - backend
      - redis

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - daniel

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      REDIS_HOST: redis
    depends_on:
      - redis
    networks:
      - daniel

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - backend
    networks:
      - daniel

networks:
  daniel:
    driver: bridge